version: "3.8"
services:
  calc:
    build: .
    image: samplecalc
    ports:
      - "3040:3040"
    environment:
      - PORT=3040
    container_name: my-calc
    networks:
      - my-calc-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
  calc1:
    build: .
    image: samplecalc
    ports:
      - "3041:3040"
    environment:
      - PORT=3040
    container_name: my-calc1
    networks:
      - my-calc-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

networks:
  my-calc-net:
    driver: bridge
